kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/quamotion/ffmpeg-arm64
    dockerfile: docker-images/4.1/ubuntu/Dockerfile