kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker
  commands:
  - docker build docker-images/4.1/ubuntu/
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock