---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/quamotion/ffmpeg
    dockerfile: docker-images/4.1/ubuntu/Dockerfile
    tags: 4.1-arm64
    build_args:
      - MAKEFLAGS="-j96"
---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: quay.io/quamotion/ffmpeg
    dockerfile: docker-images/4.1/ubuntu/Dockerfile
    tags: 4.1
    build_args:
      - MAKEFLAGS="-j24"